import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#f3ede4",
  },
  loadingWrap: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  loadingText: {
    fontSize: 14,
    color: "#4b5563",
  },
  screenContent: {
    padding: 16,
    gap: 12,
    paddingBottom: 36,
  },
  screenTitle: {
    fontSize: 26,
    fontWeight: "700",
    color: "#111827",
  },
  discountCard: {
    backgroundColor: "#fff1de",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#edd2ae",
    padding: 12,
  },
  discountName: {
    fontSize: 15,
    fontWeight: "700",
    color: "#111827",
  },
  discountDescription: {
    fontSize: 13,
    color: "#374151",
    marginTop: 4,
  },
  productCard: {
    backgroundColor: "#ffffff",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    padding: 14,
    gap: 6,
  },
  productName: {
    fontSize: 18,
    fontWeight: "700",
    color: "#111827",
  },
  productDescription: {
    fontSize: 13,
    color: "#374151",
    lineHeight: 19,
  },
  productMeta: {
    fontSize: 12,
    color: "#4b5563",
  },
  actionRow: {
    flexDirection: "row",
    gap: 8,
    marginTop: 8,
  },
  primaryButton: {
    backgroundColor: "#111827",
    borderRadius: 999,
    paddingVertical: 10,
    paddingHorizontal: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  primaryButtonText: {
    color: "#f9fafb",
    fontSize: 13,
    fontWeight: "700",
  },
  secondaryButton: {
    borderRadius: 999,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: "#d1d5db",
    alignSelf: "flex-start",
  },
  secondaryButtonText: {
    color: "#111827",
    fontSize: 13,
    fontWeight: "600",
  },
  cartLine: {
    backgroundColor: "#ffffff",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    padding: 12,
    gap: 8,
  },
  cartLineHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  quantityRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  quantityInput: {
    width: 64,
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: "#fff",
  },
  ghostButton: {
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 999,
    paddingVertical: 7,
    paddingHorizontal: 12,
  },
  ghostButtonText: {
    color: "#374151",
    fontSize: 12,
    fontWeight: "600",
  },
  sectionTotal: {
    fontSize: 22,
    fontWeight: "700",
    color: "#111827",
    marginTop: 4,
  },
  notice: {
    padding: 10,
    borderRadius: 8,
    backgroundColor: "#ecfdf5",
    color: "#065f46",
    fontSize: 12,
    borderWidth: 1,
    borderColor: "#6ee7b7",
  },
  error: {
    padding: 10,
    borderRadius: 8,
    backgroundColor: "#fef2f2",
    color: "#991b1b",
    fontSize: 12,
    borderWidth: 1,
    borderColor: "#fca5a5",
  },
  disabledButton: {
    opacity: 0.6,
  },
  checkoutCard: {
    backgroundColor: "#fff",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    padding: 12,
    gap: 6,
  },
  successTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#065f46",
  },
  errorTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#991b1b",
  },
});
